# Generated by Django 6.1 on 2026-08-28 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in KG', max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, help_text='height in meter', max_digits=5)),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activity_level', models.CharField(choices=[('sedentary', 'sedentary'), ('light', 'light'), ('moderate', 'moderate'), ('active', 'active'), ('very_active', 'very_active')], max_length=50)),
                ('goal', models.CharField(choices=[('weight_loss', 'weight_loss'), ('weight_gain', 'weight_gain'), ('maintenance', 'maintenance')], max_length=30)),
                ('profile_pic', models.ImageField(upload_to='media')),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
